export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_PUBLIC_RECIPES_START = 'GET_PUBLIC_RECIPES_START';
export const GET_PUBLIC_RECIPES_SUCCESS = 'GET_PUBLIC_RECIPES_SUCCESS';
export const GET_PUBLIC_RECIPES_FAIL = 'GET_PUBLIC_RECIPES_FAIL';
export const GET_ALL_RECIPES_START = 'GET_ALL_RECIPES_START';
export const GET_ALL_RECIPES_SUCCESS = 'GET_ALL_RECIPES_SUCCESS';
export const GET_ALL_RECIPES_FAIL = 'GET_ALL_RECIPES_FAIL';
export const GET_USER_RECIPES_START = 'GET_USER_RECIPES_START';
export const GET_USER_RECIPES_SUCCESS = 'GET_USER_RECIPES_SUCCESS';
export const GET_USER_RECIPES_FAIL = 'GET_USER_RECIPES_FAIL';
